sudo: false
language: python
cache: pip
python:
  - 3.6
addons:
  postgresql: "9.6"
install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install -r dev-requirements.txt
  - travis_retry pip install codecov
  - pip install -e .
script:
  - pytest --cov=bradley
after_success:
  - codecov
